### ISSUE TITLE
Minor: map does only partly switch to "Extra Large" size

### ISSUE THREAD

**Issue by MaEtUgR** [PX4/flight_review#30]
Here's the best explanation:
![extra_large_map](https://cloud.githubusercontent.com/assets/4668506/24148721/3f169b5a-0e40-11e7-9077-f822d848a062.PNG)

It stays like this even after moving and zooming...
I use Chrome 56.0.2924.87 (64-bit) on Windows.

**Comment by bkueng** [comment]
Fixed in https://github.com/PX4/flight_review/commit/94d1b06e60bc37d5dbe527b52092807ea05e04ad

**Comment by MaEtUgR** [comment]
Nice! But I still have this glitch online just now... is it not deployed yet?

**Comment by MaEtUgR** [comment]
Turns out I'm too impatient for the page to load completely. The problem is fixed for the "normal" case where the page has finished loading.
